-- Run this in your Supabase SQL Editor to fix the schema error

-- 1. Add the missing commission_rate column if it doesn't exist
ALTER TABLE entries 
ADD COLUMN IF NOT EXISTS commission_rate numeric DEFAULT 0.7;

-- 2. (Optional) Verify entries table exists and has correct structure
-- This is just for reference, the ALTER TABLE alone should fix your specific error.
/*
create table if not exists entries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  staff_name text not null,
  sales_amount numeric not null,
  timestamp timestamp with time zone not null,
  commission_rate numeric default 0.7,
  user_id uuid references auth.users not null
);
*/
